### ISSUE TITLE
请问二次预训练中提到的法律问答数据与指令微调训练中的法律问答数据是同一份吗？

### ISSUE THREAD

**Issue by xyfZzz** [zhihaiLLM/wisdomInterrogatory#2]
请问一下二次预训练中提到的法律问答数据与指令微调训练中的法律问答数据是同一份吗？
如果是的话，为什么需要在二次预训练中训练一次，再在指令微调训练中训练一次？
谢谢！

**Comment by wuyiquan** [comment]
不完全一致，二次预训练的目的是让模型学习法律知识，sft的目的是让模型理解指令；换句话说，预训练是让模型学内容，sft是让模型学形式。或许可以这么理解：即便是同样的数据，也在不同阶段，会发挥不同的作用。

**Comment by xyfZzz** [comment]
> 不完全一致，二次预训练的目的是让模型学习法律知识，sft的目的是让模型理解指令；换句话说，预训练是让模型学内容，sft是让模型学形式。或许可以这么理解：即便是同样的数据，也在不同阶段，会发挥不同的作用。

谢谢解答。再请问下，如果问答数据是基于二次预训练中用到的文章生成的话，那么还有必要在二次预训练中加入这部分问答数据吗？

**Comment by wuyiquan** [comment]
> > 不完全一致，二次预训练的目的是让模型学习法律知识，sft的目的是让模型理解指令；换句话说，预训练是让模型学内容，sft是让模型学形式。或许可以这么理解：即便是同样的数据，也在不同阶段，会发挥不同的作用。
> 
> 谢谢解答。再请问下，如果问答数据是基于二次预训练中用到的文章生成的话，那么还有必要在二次预训练中加入这部分问答数据吗？

对于比较重要的数据，我觉得是有用的。预训练里的数据比较杂，可以在sft时候再强调一下重要的数据。

**Comment by xyfZzz** [comment]
> > > 不完全一致，二次预训练的目的是让模型学习法律知识，sft的目的是让模型理解指令；换句话说，预训练是让模型学内容，sft是让模型学形式。或许可以这么理解：即便是同样的数据，也在不同阶段，会发挥不同的作用。
> > 
> > 
> > 谢谢解答。再请问下，如果问答数据是基于二次预训练中用到的文章生成的话，那么还有必要在二次预训练中加入这部分问答数据吗？
> 
> 对于比较重要的数据，我觉得是有用的。预训练里的数据比较杂，可以在sft时候再强调一下重要的数据。

感谢解答！但是可能是我没有表达清楚，想再确认一下：

我想问的是，问答数据基于一些文章进行生成，这些文章会在二次预训练阶段训练，这些生成的问答数据会放入SFT阶段训练，那么在这个基础上，这些生成的问答数据还有必要也放入二次预训练阶段训练么？

**Comment by wuyiquan** [comment]
> > > > 不完全一致，二次预训练的目的是让模型学习法律知识，sft的目的是让模型理解指令；换句话说，预训练是让模型学内容，sft是让模型学形式。或许可以这么理解：即便是同样的数据，也在不同阶段，会发挥不同的作用。
> > > 
> > > 
> > > 谢谢解答。再请问下，如果问答数据是基于二次预训练中用到的文章生成的话，那么还有必要在二次预训练中加入这部分问答数据吗？
> > 
> > 
> > 对于比较重要的数据，我觉得是有用的。预训练里的数据比较杂，可以在sft时候再强调一下重要的数据。
> 
> 感谢解答！但是可能是我没有表达清楚，想再确认一下：
> 
> 我想问的是，问答数据基于一些文章进行生成，这些文章会在二次预训练阶段训练，这些生成的问答数据会放入SFT阶段训练，那么在这个基础上，这些生成的问答数据还有必要也放入二次预训练阶段训练么？

我觉得是有的，知识相关的内容，最好都在预训练阶段灌输进去，sft可以认为不再给知识了，只给形式

**Comment by xyfZzz** [comment]
> > > > > 不完全一致，二次预训练的目的是让模型学习法律知识，sft的目的是让模型理解指令；换句话说，预训练是让模型学内容，sft是让模型学形式。或许可以这么理解：即便是同样的数据，也在不同阶段，会发挥不同的作用。
> > > > 
> > > > 
> > > > 谢谢解答。再请问下，如果问答数据是基于二次预训练中用到的文章生成的话，那么还有必要在二次预训练中加入这部分问答数据吗？
> > > 
> > > 
> > > 对于比较重要的数据，我觉得是有用的。预训练里的数据比较杂，可以在sft时候再强调一下重要的数据。
> > 
> > 
> > 感谢解答！但是可能是我没有表达清楚，想再确认一下：
> > 我想问的是，问答数据基于一些文章进行生成，这些文章会在二次预训练阶段训练，这些生成的问答数据会放入SFT阶段训练，那么在这个基础上，这些生成的问答数据还有必要也放入二次预训练阶段训练么？
> 
> 我觉得是有的，知识相关的内容，最好都在预训练阶段灌输进去，sft可以认为不再给知识了，只给形式

好的，感谢您的解答
