### ISSUE TITLE
二次预训练和SFT数据集是否有开源计划

### ISSUE THREAD

**Issue by songkq** [zhihaiLLM/wisdomInterrogatory#3]

**Comment by zhangyu68** [comment]
同求

**Comment by 1605wzf** [comment]
同问

**Comment by wuyiquan** [comment]
抱歉，暂时没有开源计划，因为设计到一些公司的内部数据，我们会再去协调一下看看

**Comment by r00mz** [comment]
您好，我想请教一下，根据我学到的知识（纯理论知识），在二次预训练pt和微调sft的时候epoch最好不要太大，例如1-2论即可（为了防止大模型出现幻觉），请问针对baichuan-7b可以提供我们pt和sft的参数、硬件资源否，另外没有选择qwen-7b-chat的原因是？

**Comment by songkq** [comment]
@wuyiquan 感谢解答～请问二次预训练的基座模型有开源计划吗？

**Comment by wuyiquan** [comment]
> 您好，我想请教一下，根据我学到的知识（纯理论知识），在二次预训练pt和微调sft的时候epoch最好不要太大，例如1-2论即可（为了防止大模型出现幻觉），请问针对baichuan-7b可以提供我们pt和sft的参数、硬件资源否，另外没有选择qwen-7b-chat的原因是？

一般3轮就差不多了，具体可以看luwen_baichuan/run.sh里的配置，我们做二次预训练用了16张A100 80G，sft时候会少一些。

**Comment by wuyiquan** [comment]
> @wuyiquan 感谢解答～请问二次预训练的基座模型有开源计划吗？

这个我得去问一下，如果可以的话，我会把它上传上来

**Comment by songkq** [comment]
感谢～
