### ISSUE TITLE
SFT 领域指令微调数据构建方式

### ISSUE THREAD

**Issue by yejiahaoye** [zhihaiLLM/wisdomInterrogatory#5]
能够详细说明一下SFT 领域指令微调数据构建方式， 是通过self-instruct 等方式来实现的么，能够公布一下SFT构建的代码

**Comment by wuyiquan** [comment]
你好，我们一方面是清洗了公开的领域问答数据，一方面是利用chatgpt来反向生成的sft数据，构造sft数据的prompt代码，可以参考 [luwen_baichuan/data_demo/README.md](https://github.com/zhihaiLLM/wisdomInterrogatory/blob/main/luwen_baichuan/data_demo/README.md)
