### ISSUE TITLE
能放两条两例数据吗？

### ISSUE THREAD

**Issue by kbwzy** [zhihaiLLM/wisdomInterrogatory#7]
![image](https://github.com/zhihaiLLM/wisdomInterrogatory/assets/12123683/f51ea143-cae9-428f-89b5-ef9c45ef5a21)

**Comment by wuyiquan** [comment]
{"key0": "《民法典》 第二百一十三条", "key": "《民法典》 第二百一十三条 登记机构不得有下列行为：（一）要求对不动产进行评估；（二）以年检等名义进行重复登记；（三）超出登记职责范围的其他行为。", "value": "《民法典》 第二百一十三条 登记机构不得有下列行为：（一）要求对不动产进行评估；（二）以年检等名义进行重复登记；（三）超出登记职责范围的其他行为。"}
{"key0": "《民法典》 第二百一十四条", "key": "《民法典》 第二百一十四条 不动产物权的设立、变更、转让和消灭，依照法律规定应当登记的，自记载于不动产登记簿时发生效力。", "value": "《民法典》 第二百一十四条 不动产物权的设立、变更、转让和消灭，依照法律规定应当登记的，自记载于不动产登记簿时发生效力。"}
{"key0": "《民法典》 第二百一十五条", "key": "《民法典》 第二百一十五条 当事人之间订立有关设立、变更、转让和消灭不动产物权的合同，除法律另有规定或者当事人另有约定外，自合同成立时生效；未办理物权登记的，不影响合同效力。", "value": "《民法典》 第二百一十五条 当事人之间订立有关设立、变更、转让和消灭不动产物权的合同，除法律另有规定或者当事人另有约定外，自合同成立时生效；未办理物权登记的，不影响合同效力。"}

上面是法条库的例子，每个知识库的知识格式不完全一样。完整的知识库可以在云盘里下，另外这些我们后面会有比较大的改动，现在做得比较简单。
